

ship:
  http:
    app-name: order
    version: gray_1.0
    context-path: /order
    port: 8082
    admin-url: 127.0.0.1:9001

server:
  port: 8082

nacos:
  discovery:
    server-addr: 127.0.0.1:8848